name: Build sqrtRADIO

on:
  push:
    tags:
      - 'v*' # Löst Build aus, wenn du einen Tag erstellst (z.B. v1.0.0)
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: sqrtRADIO-linux
          - os: windows-latest
            name: sqrtRADIO-windows.exe
          - os: macos-latest
            name: sqrtRADIO-macos

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: pip install pyinstaller requests sounddevice numpy

      - name: Build
        run: pyinstaller --onefile --noconsole --name ${{ matrix.name }} sqrtRADIO.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: dist/${{ matrix.name }}* # Lädt die generierte Binärdatei hoch

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
